language: cpp

compiler:
  - g++

install:
- export CXX="g++-5"

addons:
  apt:
    sources:
      - deadsnakes
      - ubuntu-toolchain-r-test

addons:
  apt:
    packages:
      - g++-5
script:
  - chmod +x find.sh
  - ./find.sh
