language: cpp

compiler:
  - g++

install:
- export CXX="g++-4.8"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

addons:
  apt:
    packages:
      - g++-4.8
script:
  - chmod +x find.sh
  - ./find.sh
